### ISSUE TITLE
Fail when I execute prestart:prod

### ISSUE THREAD

**Issue by izquierdogalan** [nestjs-community/nest-emitter#3]
npm run prestart:prod                                       

> nest-typescript-starter@1.0.0 prestart:prod /home/develop/backend
> tsc

node_modules/nest-emitter/strong-emitter.d.ts:17:82 - error TS1110: Type expected.

17 declare type ListenerType<T> = [T] extends [(...args: infer U) => any] ? U : [T, ...any[]];

**Comment by shekohex** [comment]
Which version of Typescript do you use?
And can you share your tsconfig.json!

**Comment by izquierdogalan** [comment]
Firstly I would like to give you the thanks for the support.
I use a typescript version typescript@2.9.2, I attach my tsconfig.json:

`{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "sourceMap": true,
    "allowJs": true,
    "outDir": "./dist",
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "baseUrl": ".",
    "paths": {
      "*": [
        "node_modules/*",
        "src/types/*"
      ]
    },
    "lib": [
      "es6",
      "dom",
      "esnext"
    ]
  },
  "include": [
    "src/**/*"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}`

**Comment by shekohex** [comment]
Oh, i think i mentioned in README file at install section:

> IMPORTANT: you will need typescript 3.0+

So you need to update your Typescript version to use this library.

**Comment by izquierdogalan** [comment]
Thanks I am going to try it.
