### ISSUE TITLE
Please release version 1.1.0

### ISSUE THREAD

**Issue by bashleigh** [nestjs-community/nest-emitter#8]
#6 #4

**Comment by bashleigh** [comment]
Plez 

![pleaze](https://sayingimages.com/wp-content/uploads/spongebob-begging-please-meme.jpg)

**Comment by shekohex** [comment]
### No :joy: 
![2](https://user-images.githubusercontent.com/14620076/57020531-d389e780-6c29-11e9-9d7d-3ae37c1989df.jpg)

**Comment by shekohex** [comment]
Okay, Published `v1.1.0` :tada:

**Comment by bashleigh** [comment]
![thanks](https://www.humorside.com/wp-content/uploads/2017/12/thank-you-meme-04.jpg)
